services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: courseapp
      POSTGRES_USER: courseuser
      POSTGRES_PASSWORD: coursepass
    ports:
      - "5433:5432"   # HOST:CONTAINER → host portu 5433
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
